spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/medicalrepresentative
    username:  
    password:
    initialization-mode: always
  h2:
    enabled: true
  jpa:  
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  
  application:
    name: rep-schedule

server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://65.1.180.5:8761/eureka/
  
management:
  security:
    enabled:
      false
security:
  basic:
    enabled:
      true


feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
      
logging:
  level:
    org:
      hibernate:
        SQL: trace
      type:
        descriptor:
          sql: trace

# Log pattern 
  pattern:
    console: "%d{dd-MM-yy} %d{HH:mm:ss.SSS} %-20.20thread %5p %-25.25logger{25} %25M %4L %m%n"
    